import type { Activity, PlayerProgress, Zone } from "@/lib/game-types";

export const DEFAULT_PROGRESS: PlayerProgress = {
  childName: "Mia",
  sessionsCompleted: 2,
  seeds: 7,
  streak: 3,
  masteredLetters: ["m", "s", "a", "t"],
  masteredWords: ["sat", "mat"],
  gardenLevel: 2,
  soundOn: true,
  reducedMotion: false,
  lastPlayed: null,
};

export const ZONES: Zone[] = [
  {
    id: "sound-safari",
    name: "Sound Safari",
    eyebrow: "Listen & play",
    description: "Rhyme, clap and find the sounds hiding in words.",
    color: "#F7C56A",
    glow: "rgba(247, 197, 106, .52)",
    icon: "♪",
    requiredSeeds: 0,
  },
  {
    id: "letter-lanterns",
    name: "Letter Lanterns",
    eyebrow: "Sounds meet letters",
    description: "Light a lantern by matching each sound to its letter.",
    color: "#E88B78",
    glow: "rgba(232, 139, 120, .48)",
    icon: "m",
    requiredSeeds: 2,
  },
  {
    id: "blend-bridge",
    name: "Blend Bridge",
    eyebrow: "Stretch & blend",
    description: "Sweep across the stones and join sounds into words.",
    color: "#6FB6C6",
    glow: "rgba(111, 182, 198, .5)",
    icon: "⌁",
    requiredSeeds: 5,
  },
  {
    id: "word-garden",
    name: "Word Garden",
    eyebrow: "Build & change",
    description: "Plant letter tiles and watch new words grow.",
    color: "#84B66B",
    glow: "rgba(132, 182, 107, .5)",
    icon: "✿",
    requiredSeeds: 8,
  },
  {
    id: "story-stage",
    name: "Story Stage",
    eyebrow: "Read a tiny tale",
    description: "Bring a little story to life, one brave word at a time.",
    color: "#9C8AC7",
    glow: "rgba(156, 138, 199, .5)",
    icon: "★",
    requiredSeeds: 11,
  },
];

export const ACTIVITIES: Activity[] = [
  {
    id: "sound-safari",
    title: "Sound Safari",
    eyebrow: "Warm-up · Rhyming",
    instruction: "Listen for the word that ends the same way.",
    prompt: "Which picture rhymes with star?",
    helper: "Star… /ar/. Find another word with /ar/.",
    options: [
      { id: "car", label: "Car", spokenLabel: "car", icon: "🚗", correct: true },
      { id: "moon", label: "Moon", spokenLabel: "moon", icon: "🌙", correct: false },
      { id: "fish", label: "Fish", spokenLabel: "fish", icon: "🐟", correct: false },
    ],
    celebration: "Star and car rhyme. You heard the matching ending!",
    skill: "Rhyming words",
  },
  {
    id: "letter-lanterns",
    title: "Letter Lanterns",
    eyebrow: "Focus · Letter sound",
    instruction: "Tap the letter that makes Pip’s sound.",
    prompt: "Mmm… like moon. Which letter says /m/?",
    helper: "Put your lips together: mmm. Now look for lowercase m.",
    options: [
      { id: "s", label: "s", spokenLabel: "s", correct: false },
      { id: "m", label: "m", spokenLabel: "m", correct: true },
      { id: "t", label: "t", spokenLabel: "t", correct: false },
    ],
    celebration: "M says /m/. That lantern is glowing!",
    skill: "Letter–sound: m",
    letters: ["s", "m", "t"],
  },
  {
    id: "blend-bridge",
    title: "Blend Bridge",
    eyebrow: "Focus · Smooth blending",
    instruction: "Slide across the sounds, then choose the word.",
    prompt: "/mmm/ … /aaa/ … /t/. What word?",
    helper: "Keep the sounds touching: mmmaaat… mat.",
    options: [
      { id: "mat", label: "Mat", spokenLabel: "mat", icon: "▦", correct: true },
      { id: "sun", label: "Sun", spokenLabel: "sun", icon: "☀️", correct: false },
      { id: "cat", label: "Cat", spokenLabel: "cat", icon: "🐈", correct: false },
    ],
    celebration: "Mmm–aaa–t… mat! You carried every sound across.",
    skill: "Blend CVC word: mat",
    letters: ["m", "a", "t"],
  },
  {
    id: "word-garden",
    title: "Word Garden",
    eyebrow: "Practice · Change one sound",
    instruction: "Change one letter to grow a new word.",
    prompt: "Change sat into sit. Which vowel belongs in the middle?",
    helper: "Say sit slowly: /s/ /i/ /t/. Listen to the middle.",
    options: [
      { id: "a", label: "a", spokenLabel: "a", correct: false },
      { id: "i", label: "i", spokenLabel: "i", correct: true },
      { id: "o", label: "o", spokenLabel: "o", correct: false },
    ],
    celebration: "S–i–t makes sit. A whole new word just bloomed!",
    skill: "Medial vowel substitution",
    letters: ["s", "_", "t"],
  },
  {
    id: "story-stage",
    title: "Story Stage",
    eyebrow: "Finale · Tiny story",
    instruction: "Read with Pip, then answer the story question.",
    prompt: "Who sat with Sam?",
    helper: "Look back at the second sentence. Who sat?",
    options: [
      { id: "cat", label: "The cat", spokenLabel: "the cat", icon: "🐈", correct: true },
      { id: "dog", label: "The dog", spokenLabel: "the dog", icon: "🐕", correct: false },
      { id: "fox", label: "Pip", spokenLabel: "Pip the fox", icon: "🦊", correct: false },
    ],
    celebration: "Yes, the cat sat with Sam. You read for meaning!",
    skill: "Connected text & comprehension",
    storyWords: ["Sam", "sat.", "A", "cat", "sat", "with", "Sam."],
  },
];

export const SKILL_ROWS = [
  { name: "Rhyming words", status: "Secure", score: 92, color: "#E9A84C" },
  { name: "Letter sounds · m s a t", status: "Secure", score: 86, color: "#DF806C" },
  { name: "Smooth blending", status: "Practicing", score: 68, color: "#5EAAB8" },
  { name: "CVC word building", status: "Learning", score: 52, color: "#73A95B" },
  { name: "Tiny-story meaning", status: "New", score: 28, color: "#8E7AB9" },
];
