import type { Activity, PlayerProgress, Zone } from "@/lib/game-types";

export const DEFAULT_PROGRESS: PlayerProgress = {
  childName: "Mia",
  sessionsCompleted: 2,
  seeds: 7,
  streak: 3,
  masteredLetters: ["m", "s", "a", "t"],
  masteredWords: ["sat", "mat"],
  gardenLevel: 2,
  soundOn: true,
  reducedMotion: false,
  lastPlayed: null,
  completedAdventureIds: ["echo-picnic", "moon-mouse"],
  plantedSeedIds: ["moonflower", "sunbell"],
  unlockedStickerIds: ["echo-shell", "moon-mouse"],
  readStoryIds: [],
  totalStars: 9,
  dailyQuestDate: null,
};

export const ZONES: Zone[] = [
  {
    id: "sound-safari",
    name: "Echo Meadow",
    eyebrow: "Listen & play",
    description: "Rhyme, clap and find the sounds hiding in words.",
    color: "#F7C56A",
    glow: "rgba(247, 197, 106, .52)",
    icon: "♪",
    requiredSeeds: 0,
  },
  {
    id: "letter-lanterns",
    name: "Lantern Grove",
    eyebrow: "Sounds meet letters",
    description: "Light a lantern by matching each sound to its letter.",
    color: "#E88B78",
    glow: "rgba(232, 139, 120, .48)",
    icon: "m",
    requiredSeeds: 2,
  },
  {
    id: "blend-bridge",
    name: "Blend Brook",
    eyebrow: "Stretch & blend",
    description: "Sweep across the stones and join sounds into words.",
    color: "#6FB6C6",
    glow: "rgba(111, 182, 198, .5)",
    icon: "⌁",
    requiredSeeds: 5,
  },
  {
    id: "word-garden",
    name: "Word Garden",
    eyebrow: "Build & change",
    description: "Plant letter tiles and watch new words grow.",
    color: "#84B66B",
    glow: "rgba(132, 182, 107, .5)",
    icon: "✿",
    requiredSeeds: 8,
  },
  {
    id: "story-stage",
    name: "Story Theater",
    eyebrow: "Read a tiny tale",
    description: "Bring a little story to life, one brave word at a time.",
    color: "#9C8AC7",
    glow: "rgba(156, 138, 199, .5)",
    icon: "★",
    requiredSeeds: 11,
  },
];

export const ACTIVITIES: Activity[] = [
  {
    key: "featured-sound",
    id: "sound-safari",
    kind: "rhyme",
    title: "Sound Safari",
    eyebrow: "Warm-up · Rhyming",
    instruction: "Listen for the word that ends the same way.",
    prompt: "Which picture rhymes with star?",
    helper: "Listen to the ends: st-ar, c-ar.",
    options: [
      { id: "car", label: "Car", spokenLabel: "car", icon: "🚗", correct: true },
      { id: "moon", label: "Moon", spokenLabel: "moon", icon: "🌙", correct: false },
      { id: "fish", label: "Fish", spokenLabel: "fish", icon: "🐟", correct: false },
    ],
    celebration: "Star and car rhyme. You heard the matching ending!",
    skill: "Rhyming words",
    voice: {
      prompt: "sound.prompt",
      hints: ["sound.hint.1", "sound.hint.2"],
      correct: "sound.correct",
      wrong: {
        moon: "sound.wrong.moon",
        fish: "sound.wrong.fish",
      },
    },
    bubble: {
      prompt: "Which picture has the same bouncy ending as star?",
      hints: ["Listen to the ends: st-ar, c-ar.", "Star, car! Tap the little car."],
      correct: "Star and car rhyme. Your listening ears caught it!",
      wrong: {
        moon: "Moon ends with oo. We need a word ending in ar.",
        fish: "Fish ends with ish. We need a word ending in ar.",
      },
    },
  },
  {
    key: "featured-letter",
    id: "letter-lanterns",
    kind: "letter",
    title: "Letter Lanterns",
    eyebrow: "Focus · Letter sound",
    instruction: "Tap the letter that makes Pip’s sound.",
    prompt: "Mmmmm… like moon. Which lowercase letter makes that sound?",
    helper: "Close your lips and hum. Look for the letter with two little hills.",
    options: [
      { id: "s", label: "s", spokenLabel: "s", correct: false },
      { id: "m", label: "m", spokenLabel: "m", correct: true },
      { id: "t", label: "t", spokenLabel: "t", correct: false },
    ],
    celebration: "Mmmmm, marvelous! That lantern is glowing!",
    skill: "Letter–sound: m",
    letters: ["s", "m", "t"],
    voice: {
      prompt: "letter.prompt",
      hints: ["letter.hint.1", "letter.hint.2"],
      correct: "letter.correct",
      wrong: {
        s: "letter.wrong.s",
        t: "letter.wrong.t",
      },
    },
    bubble: {
      prompt: "Hum with me: mmmmm. Which lowercase letter makes that sound?",
      hints: ["Closed lips, gentle hum. Look for two little hills.", "That humming sound belongs to lowercase m."],
      correct: "Mmmmm, marvelous! You lit the m lantern.",
      wrong: {
        s: "That one makes a snake sound. We need the humming sound.",
        t: "That one makes a quick tap. We need the humming sound.",
      },
    },
  },
  {
    key: "featured-blend",
    id: "blend-bridge",
    kind: "blend",
    title: "Blend Bridge",
    eyebrow: "Focus · Smooth blending",
    instruction: "Slide across the sounds, then choose the word.",
    prompt: "Mmmmm… aaaaa… t. Sweep the sounds together. What word?",
    helper: "Keep the sounds touching: mmmmm-aaaaa-t. Mat.",
    options: [
      { id: "mat", label: "Mat", spokenLabel: "mat", icon: "▦", correct: true },
      { id: "sun", label: "Sun", spokenLabel: "sun", icon: "☀️", correct: false },
      { id: "cat", label: "Cat", spokenLabel: "cat", icon: "🐈", correct: false },
    ],
    celebration: "Mmm–aaa–t… mat! You carried every sound across.",
    skill: "Blend CVC word: mat",
    letters: ["m", "a", "t"],
    voice: {
      prompt: "blend.prompt",
      hints: ["blend.hint.1", "blend.hint.2"],
      correct: "blend.correct",
      wrong: {
        sun: "blend.wrong.sun",
        cat: "blend.wrong.cat",
      },
    },
    bubble: {
      prompt: "Keep the sounds touching: mmmmm-aaaaa-t. What word?",
      hints: ["Sweep faster: mmmmm-aaaaa-t. Mat.", "The word starts with the humming sound mmmmm."],
      correct: "Mat! You swept every sound across the bridge.",
      wrong: {
        sun: "Sun starts with sssss. Our word starts with mmmmm.",
        cat: "Cat starts with kuh. Our word starts with mmmmm.",
      },
    },
  },
  {
    key: "featured-word",
    id: "word-garden",
    kind: "word",
    title: "Word Garden",
    eyebrow: "Practice · Change one sound",
    instruction: "Change one letter to grow a new word.",
    prompt: "Change sat into sit. Which vowel belongs in the middle?",
    helper: "Say sit slowly: sss-ih-t. Listen to the middle.",
    options: [
      { id: "a", label: "a", spokenLabel: "a", correct: false },
      { id: "i", label: "i", spokenLabel: "i", correct: true },
      { id: "o", label: "o", spokenLabel: "o", correct: false },
    ],
    celebration: "S–i–t makes sit. A whole new word just bloomed!",
    skill: "Medial vowel substitution",
    letters: ["s", "_", "t"],
    voice: {
      prompt: "word.prompt",
      hints: ["word.hint.1", "word.hint.2"],
      correct: "word.correct",
      wrong: {
        a: "word.wrong.a",
        o: "word.wrong.o",
      },
    },
    bubble: {
      prompt: "Change sat into sit. Which letter makes the quick middle sound?",
      hints: ["Stretch it: sss-ih-t. Listen to the middle.", "Plant lowercase i between s and t."],
      correct: "Sit! One tiny sound grew a whole new word.",
      wrong: {
        a: "A keeps the old word sat. Listen for ih in sit.",
        o: "O would make sot. Listen for ih in sit.",
      },
    },
  },
  {
    key: "featured-story",
    id: "story-stage",
    kind: "story",
    title: "Story Stage",
    eyebrow: "Finale · Tiny story",
    instruction: "Read with Pip, then answer the story question.",
    prompt: "Who sat with Sam?",
    helper: "Look back at the second sentence. Who sat?",
    options: [
      { id: "cat", label: "The cat", spokenLabel: "the cat", icon: "🐈", correct: true },
      { id: "dog", label: "The dog", spokenLabel: "the dog", icon: "🐕", correct: false },
      { id: "fox", label: "Pip", spokenLabel: "Pip the fox", icon: "🦊", correct: false },
    ],
    celebration: "Yes, the cat sat with Sam. You read for meaning!",
    skill: "Connected text & comprehension",
    storyWords: ["Sam", "sat.", "A", "cat", "sat", "with", "Sam."],
    voice: {
      prompt: "story.prompt",
      hints: ["story.hint.1", "story.hint.2"],
      correct: "story.correct",
      wrong: {
        dog: "story.wrong.dog",
        fox: "story.wrong.fox",
      },
    },
    bubble: {
      prompt: "Sam sat. A cat sat with Sam. Who sat with Sam?",
      hints: ["Look at the second sentence. Which animal did it name?", "The story says: A cat sat with Sam."],
      correct: "The cat! You read the words and remembered their meaning.",
      wrong: {
        dog: "The story never named a dog. Check the second sentence.",
        fox: "Pip is cheering, but he was not in this tiny story.",
      },
    },
  },
];

export const SKILL_ROWS = [
  { name: "Rhyming words", status: "Secure", score: 92, color: "#E9A84C" },
  { name: "Letter sounds · m s a t", status: "Secure", score: 86, color: "#DF806C" },
  { name: "Smooth blending", status: "Practicing", score: 68, color: "#5EAAB8" },
  { name: "CVC word building", status: "Learning", score: 52, color: "#73A95B" },
  { name: "Tiny-story meaning", status: "New", score: 28, color: "#8E7AB9" },
];
