import type {
  Activity,
  Adventure,
  AnswerOption,
  LibraryStory,
  Sticker,
  ZoneId,
} from "@/lib/game-types";
import type { VoiceLine, VoiceMood } from "@/lib/voice-lines";

interface ActivitySeed {
  key: string;
  regionId: ZoneId;
  kind: Activity["kind"];
  title: string;
  prompt: string;
  helper: string;
  options: Array<AnswerOption>;
  celebration: string;
  skill: string;
  spokenPrompt?: string;
  spokenHint?: string;
  letters?: string[];
  storyWords?: string[];
}

export const WORLD_VOICE_LINES: Record<string, VoiceLine> = {};

const INSTRUCTIONS: Record<Activity["kind"], string> = {
  rhyme: "Find the words with matching endings.",
  sound: "Listen closely to the sound hiding in each word.",
  letter: "Match Pip’s sound to its lowercase letter.",
  blend: "Sweep the sounds together to make a word.",
  word: "Change or build a word with one letter.",
  story: "Read the tiny tale, then answer from the story.",
};

const EYEBROWS: Record<Activity["kind"], string> = {
  rhyme: "Echo hunt · Rhyming",
  sound: "Sound detective · First sounds",
  letter: "Lantern puzzle · Letter sound",
  blend: "Brook crossing · Smooth blend",
  word: "Garden puzzle · Word building",
  story: "Curtain up · Story meaning",
};

function line(id: string, text: string, mood: VoiceMood) {
  WORLD_VOICE_LINES[id] = { text, mood };
  return id;
}

function makeActivity(seed: ActivitySeed): Activity {
  const promptId = line(
    `world.${seed.key}.prompt`,
    seed.spokenPrompt ?? seed.prompt,
    seed.kind === "story" ? "story" : "curious",
  );
  const hintOneId = line(
    `world.${seed.key}.hint.1`,
    seed.spokenHint ?? seed.helper,
    "coach",
  );
  const hintTwoId = line(
    `world.${seed.key}.hint.2`,
    `${seed.helper} I will make it easier: two choices that do not fit will fade as you try.`,
    "coach",
  );
  const correctId = line(
    `world.${seed.key}.correct`,
    seed.celebration,
    "celebrate",
  );
  const wrong: Record<string, string> = {};
  const wrongBubble: Record<string, string> = {};

  seed.options
    .filter((option) => !option.correct)
    .forEach((option) => {
      wrong[option.id] = line(
        `world.${seed.key}.wrong.${option.id}`,
        `Good thinking. That choice does not match this time. ${seed.helper}`,
        "coach",
      );
      wrongBubble[option.id] = `Good try. ${seed.helper}`;
    });

  return {
    key: seed.key,
    id: seed.regionId,
    kind: seed.kind,
    title: seed.title,
    eyebrow: EYEBROWS[seed.kind],
    instruction: INSTRUCTIONS[seed.kind],
    prompt: seed.prompt,
    helper: seed.helper,
    options: seed.options,
    celebration: seed.celebration,
    skill: seed.skill,
    letters: seed.letters,
    storyWords: seed.storyWords,
    voice: {
      prompt: promptId,
      hints: [hintOneId, hintTwoId],
      correct: correctId,
      wrong,
    },
    bubble: {
      prompt: seed.prompt,
      hints: [seed.helper, `${seed.helper} Watch as choices fade away.`],
      correct: seed.celebration,
      wrong: wrongBubble,
    },
  };
}

function option(
  id: string,
  label: string,
  icon: string | undefined,
  correct = false,
): AnswerOption {
  return { id, label, spokenLabel: label, icon, correct };
}

function adventure(
  id: string,
  regionId: ZoneId,
  chapter: number,
  title: string,
  description: string,
  rewardStickerId: string,
  rewardName: string,
  activities: ActivitySeed[],
  storyId?: string,
): Adventure {
  return {
    id,
    regionId,
    chapter,
    title,
    description,
    minutes: 5,
    difficulty: chapter as 1 | 2 | 3 | 4,
    rewardStickerId,
    rewardName,
    storyId,
    activities: activities.map(makeActivity),
  };
}

export const ADVENTURES: Adventure[] = [
  adventure(
    "echo-picnic",
    "sound-safari",
    1,
    "The Echo Picnic",
    "Wake three sleepy echoes with words that rhyme.",
    "echo-shell",
    "Echo Shell",
    [
      {
        key: "echo-picnic-sun",
        regionId: "sound-safari",
        kind: "rhyme",
        title: "Sunny Echo",
        prompt: "Which picture rhymes with sun?",
        helper: "Sun and fun both finish with un.",
        options: [option("fun", "Fun", "🎉", true), option("fish", "Fish", "🐟"), option("moon", "Moon", "🌙")],
        celebration: "Sun, fun! You woke the first echo.",
        skill: "Hear matching endings",
      },
      {
        key: "echo-picnic-log",
        regionId: "sound-safari",
        kind: "rhyme",
        title: "Pond Echo",
        prompt: "Which animal rhymes with log?",
        helper: "Stretch the endings: l-og, fr-og.",
        options: [option("frog", "Frog", "🐸", true), option("cat", "Cat", "🐈"), option("bee", "Bee", "🐝")],
        celebration: "Log, frog! The pond answered back.",
        skill: "Hear matching endings",
      },
      {
        key: "echo-picnic-star",
        regionId: "sound-safari",
        kind: "rhyme",
        title: "Twilight Echo",
        prompt: "What rhymes with star?",
        helper: "Listen to the word tails: st-ar, c-ar.",
        options: [option("car", "Car", "🚗", true), option("boat", "Boat", "⛵"), option("hat", "Hat", "🎩")],
        celebration: "Star, car! The whole meadow is singing.",
        skill: "Hear matching endings",
      },
    ],
  ),
  adventure(
    "rhyme-river",
    "sound-safari",
    2,
    "Rhyme River Rescue",
    "Build a trail of rhymes across a giggling stream.",
    "rhyme-frog",
    "Rhyme Frog",
    [
      {
        key: "rhyme-river-cake",
        regionId: "sound-safari",
        kind: "rhyme",
        title: "Cake Crossing",
        prompt: "Which creature rhymes with cake?",
        helper: "Cake and snake share the ending ake.",
        options: [option("snake", "Snake", "🐍", true), option("mouse", "Mouse", "🐭"), option("fox", "Fox", "🦊")],
        celebration: "Cake, snake! One stepping stone appeared.",
        skill: "Rhyme recognition",
      },
      {
        key: "rhyme-river-bee",
        regionId: "sound-safari",
        kind: "rhyme",
        title: "Buzzy Bank",
        prompt: "What rhymes with bee?",
        helper: "Bee and tree finish with the same ee sound.",
        options: [option("tree", "Tree", "🌳", true), option("boat", "Boat", "⛵"), option("bell", "Bell", "🔔")],
        celebration: "Bee, tree! The river made a happy buzz.",
        skill: "Rhyme recognition",
      },
      {
        key: "rhyme-river-fox",
        regionId: "sound-safari",
        kind: "rhyme",
        title: "Fox’s Box",
        prompt: "Which object rhymes with fox?",
        helper: "Fox and box both finish with ox.",
        options: [option("box", "Box", "📦", true), option("cup", "Cup", "🥤"), option("key", "Key", "🔑")],
        celebration: "Fox, box! The rhyme trail reached the shore.",
        skill: "Rhyme recognition",
      },
    ],
    "fox-box",
  ),
  adventure(
    "sound-detectives",
    "sound-safari",
    3,
    "The Sound Detectives",
    "Follow first-sound clues to find Pip’s missing picnic basket.",
    "detective-badge",
    "Sound Detective Badge",
    [
      {
        key: "detective-moon",
        regionId: "sound-safari",
        kind: "sound",
        title: "Moon Clue",
        prompt: "Moon begins with mmmmm. What else begins the same way?",
        helper: "Close your lips and hum the first sound.",
        spokenPrompt: "Moon begins with mmmmm. Which picture also begins with mmmmm?",
        options: [option("mouse", "Mouse", "🐭", true), option("sun", "Sun", "☀️"), option("fish", "Fish", "🐟")],
        celebration: "Moon, mouse! Both begin with mmmmm.",
        skill: "Match first sounds",
      },
      {
        key: "detective-sun",
        regionId: "sound-safari",
        kind: "sound",
        title: "Sunny Clue",
        prompt: "Sun begins with sssss. What else begins the same way?",
        helper: "Use a quiet snake sound: sssss.",
        spokenPrompt: "Sun begins with sssss. Which picture also begins with sssss?",
        options: [option("sock", "Sock", "🧦", true), option("map", "Map", "🗺️"), option("top", "Top", "🔝")],
        celebration: "Sun, sock! Your sound clue worked.",
        skill: "Match first sounds",
      },
      {
        key: "detective-fish",
        regionId: "sound-safari",
        kind: "sound",
        title: "Fishy Clue",
        prompt: "Fish begins with fffff. What else begins the same way?",
        helper: "Let the air brush your lip: fffff.",
        spokenPrompt: "Fish begins with fffff. Which picture also begins with fffff?",
        options: [option("fan", "Fan", "🪭", true), option("cat", "Cat", "🐈"), option("bell", "Bell", "🔔")],
        celebration: "Fish, fan! You found Pip’s basket.",
        skill: "Match first sounds",
      },
    ],
  ),
  adventure(
    "echo-festival",
    "sound-safari",
    4,
    "The Grand Echo Festival",
    "Conduct the meadow’s trickiest rhyming concert.",
    "golden-harp",
    "Golden Echo Harp",
    [
      {
        key: "festival-boat",
        regionId: "sound-safari",
        kind: "rhyme",
        title: "Boat Song",
        prompt: "Which animal rhymes with boat?",
        helper: "Boat and goat share the ending oat.",
        options: [option("goat", "Goat", "🐐", true), option("dog", "Dog", "🐕"), option("owl", "Owl", "🦉")],
        celebration: "Boat, goat! A perfect festival pair.",
        skill: "Independent rhyming",
      },
      {
        key: "festival-light",
        regionId: "sound-safari",
        kind: "rhyme",
        title: "Firefly Song",
        prompt: "What rhymes with light?",
        helper: "Light and kite both finish with ite.",
        options: [option("kite", "Kite", "🪁", true), option("lamp", "Lamp", "🏮"), option("leaf", "Leaf", "🍃")],
        celebration: "Light, kite! The fireflies flashed.",
        skill: "Independent rhyming",
      },
      {
        key: "festival-bell",
        regionId: "sound-safari",
        kind: "rhyme",
        title: "Final Bell",
        prompt: "Which treasure rhymes with bell?",
        helper: "Bell and shell finish with ell.",
        options: [option("shell", "Shell", "🐚", true), option("star", "Star", "⭐"), option("ring", "Ring", "💍")],
        celebration: "Bell, shell! You conducted the whole meadow.",
        skill: "Independent rhyming",
      },
    ],
  ),
  adventure(
    "moon-mouse",
    "letter-lanterns",
    1,
    "Moon Mouse’s Lantern",
    "Help a tiny mouse light the lantern for lowercase m.",
    "moon-mouse",
    "Moon Mouse",
    [
      {
        key: "moon-mouse-m",
        regionId: "letter-lanterns",
        kind: "letter",
        title: "Humming Lantern",
        prompt: "Which lowercase letter makes the humming sound mmmmm?",
        helper: "Close your lips and look for two little hills.",
        spokenPrompt: "Close your lips and hum: mmmmm. Which lowercase letter makes that sound?",
        options: [option("m", "m", undefined, true), option("s", "s", undefined), option("t", "t", undefined)],
        celebration: "Mmmmm, marvelous! The m lantern glows.",
        skill: "Letter sound m",
        letters: ["m"],
      },
      {
        key: "moon-mouse-picture",
        regionId: "letter-lanterns",
        kind: "sound",
        title: "Moon Mouse’s Snack",
        prompt: "Which snack begins with mmmmm?",
        helper: "Hum the beginning: mmmmmuffin.",
        spokenPrompt: "Which snack begins with the humming sound mmmmm?",
        options: [option("muffin", "Muffin", "🧁", true), option("apple", "Apple", "🍎"), option("toast", "Toast", "🍞")],
        celebration: "Mmmmmuffin! Moon Mouse found her snack.",
        skill: "Initial sound m",
      },
      {
        key: "moon-mouse-match",
        regionId: "letter-lanterns",
        kind: "letter",
        title: "Lantern Row",
        prompt: "Tap lowercase m one more time.",
        helper: "Find the letter with a downstroke and two humps.",
        spokenPrompt: "Find lowercase m, the letter for mmmmm.",
        options: [option("n", "n", undefined), option("m", "m", undefined, true), option("w", "w", undefined)],
        celebration: "You found m twice. Moon Mouse can see the path home.",
        skill: "Recognize lowercase m",
        letters: ["m"],
      },
    ],
    "moon-mouse-story",
  ),
  adventure(
    "snake-secret",
    "letter-lanterns",
    2,
    "The Snake’s Secret",
    "Follow a silver snake sound through the lantern leaves.",
    "silver-snake",
    "Silver Snake",
    [
      {
        key: "snake-secret-s",
        regionId: "letter-lanterns",
        kind: "letter",
        title: "Silver Lantern",
        prompt: "Which lowercase letter makes the quiet snake sound sssss?",
        helper: "Trace the curvy letter that looks like a tiny snake.",
        spokenPrompt: "Make a quiet snake sound: sssss. Which lowercase letter matches?",
        options: [option("s", "s", undefined, true), option("m", "m", undefined), option("t", "t", undefined)],
        celebration: "Sssss, splendid! The s lantern sparkles.",
        skill: "Letter sound s",
        letters: ["s"],
      },
      {
        key: "snake-secret-sun",
        regionId: "letter-lanterns",
        kind: "sound",
        title: "Sunbeam Clue",
        prompt: "Which picture begins with sssss?",
        helper: "Whisper each beginning and listen for the snake sound.",
        spokenPrompt: "Which picture begins with sssss?",
        options: [option("sun", "Sun", "☀️", true), option("moon", "Moon", "🌙"), option("cat", "Cat", "🐈")],
        celebration: "Sssssun! The secret path appeared.",
        skill: "Initial sound s",
      },
      {
        key: "snake-secret-sort",
        regionId: "letter-lanterns",
        kind: "sound",
        title: "Secret Basket",
        prompt: "Which word does not begin with sssss?",
        helper: "Sock and star begin with sssss. Listen for the different one.",
        spokenPrompt: "Sock. Star. Moon. Which word does not begin with sssss?",
        options: [option("moon", "Moon", "🌙", true), option("sock", "Sock", "🧦"), option("star", "Star", "⭐")],
        celebration: "Moon begins with mmmmm. You sorted the sounds.",
        skill: "Contrast first sounds",
      },
    ],
  ),
  adventure(
    "tapping-t",
    "letter-lanterns",
    3,
    "Turtle’s Tapping Tune",
    "Tap out the quick t sound to wake a musical turtle.",
    "tapping-turtle",
    "Tapping Turtle",
    [
      {
        key: "tapping-t-letter",
        regionId: "letter-lanterns",
        kind: "letter",
        title: "Tapping Lantern",
        prompt: "Which lowercase letter makes the quick tapping sound t?",
        helper: "Look for the tall line wearing a little crossbar.",
        spokenPrompt: "Listen to the quick sound: t, t, t. Which lowercase letter matches?",
        options: [option("t", "t", undefined, true), option("f", "f", undefined), option("m", "m", undefined)],
        celebration: "T, t, terrific! The turtle tapped back.",
        skill: "Letter sound t",
        letters: ["t"],
      },
      {
        key: "tapping-t-top",
        regionId: "letter-lanterns",
        kind: "sound",
        title: "Spinning Top",
        prompt: "Which picture begins with the quick t sound?",
        helper: "Say each name. Top begins with t.",
        spokenPrompt: "Which picture begins with t, the quick tapping sound?",
        options: [option("top", "Top", "🌀", true), option("sun", "Sun", "☀️"), option("map", "Map", "🗺️")],
        celebration: "T-top! The turtle’s tune is spinning.",
        skill: "Initial sound t",
      },
      {
        key: "tapping-t-finish",
        regionId: "letter-lanterns",
        kind: "sound",
        title: "Last Tap",
        prompt: "Which word ends with the quick t sound?",
        helper: "Say cat slowly and listen to its last sound.",
        spokenPrompt: "Which word ends with t, the quick tapping sound?",
        options: [option("cat", "Cat", "🐈", true), option("sun", "Sun", "☀️"), option("map", "Map", "🗺️")],
        celebration: "Ca-t ends with t. The tune is complete.",
        skill: "Final sound t",
      },
    ],
  ),
  adventure(
    "vowel-fireflies",
    "letter-lanterns",
    4,
    "The Vowel Fireflies",
    "Catch the quick middle sounds that make words glow.",
    "vowel-firefly",
    "Vowel Firefly",
    [
      {
        key: "vowel-fireflies-a",
        regionId: "letter-lanterns",
        kind: "letter",
        title: "Apple Glow",
        prompt: "Which lowercase vowel makes the middle sound in map?",
        helper: "Stretch map: mmmmm-aaaaa-p.",
        spokenPrompt: "Stretch the word map: mmmmm-aaaaa-p. Which lowercase vowel is in the middle?",
        options: [option("a", "a", undefined, true), option("i", "i", undefined), option("o", "o", undefined)],
        celebration: "A is the middle of map. One firefly glows.",
        skill: "Short vowel a",
        letters: ["m", "a", "p"],
      },
      {
        key: "vowel-fireflies-i",
        regionId: "letter-lanterns",
        kind: "letter",
        title: "Itty-Bitty Glow",
        prompt: "Which lowercase vowel makes the middle sound in sit?",
        helper: "Stretch sit: sssss-ih-t.",
        spokenPrompt: "Stretch the word sit: sssss-ih-t. Which lowercase vowel is in the middle?",
        options: [option("i", "i", undefined, true), option("a", "a", undefined), option("o", "o", undefined)],
        celebration: "I is the middle of sit. Two fireflies glow.",
        skill: "Short vowel i",
        letters: ["s", "i", "t"],
      },
      {
        key: "vowel-fireflies-o",
        regionId: "letter-lanterns",
        kind: "letter",
        title: "Otter Glow",
        prompt: "Which lowercase vowel makes the middle sound in log?",
        helper: "Stretch log: lll-ooo-g.",
        spokenPrompt: "Stretch the word log: lll-ooo-g. Which lowercase vowel is in the middle?",
        options: [option("o", "o", undefined, true), option("a", "a", undefined), option("i", "i", undefined)],
        celebration: "O is the middle of log. The whole grove glows.",
        skill: "Short vowel o",
        letters: ["l", "o", "g"],
      },
    ],
  ),
  adventure(
    "mat-crossing",
    "blend-bridge",
    1,
    "The Mat Crossing",
    "Keep three sounds touching to cross Blend Brook.",
    "brook-boat",
    "Leaf Boat",
    [
      {
        key: "mat-crossing-mat",
        regionId: "blend-bridge",
        kind: "blend",
        title: "First Stones",
        prompt: "Sweep m, a, t together. Which word do they make?",
        helper: "Keep the sounds touching: mmmmm-aaaaa-t. Mat.",
        spokenPrompt: "Do not say the letter names. Sweep the sounds together: mmmmm-aaaaa-t. Mat. Which word did you hear?",
        options: [option("mat", "Mat", "▦", true), option("sun", "Sun", "☀️"), option("cat", "Cat", "🐈")],
        celebration: "Mat! You crossed the first stones.",
        skill: "Blend mat",
        letters: ["m", "a", "t"],
      },
      {
        key: "mat-crossing-map",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Map Stones",
        prompt: "Sweep m, a, p together. Which word do they make?",
        helper: "Blend without gaps: mmmmm-aaaaa-p. Map.",
        spokenPrompt: "Sweep these sounds together: mmmmm-aaaaa-p. Map. Which word did you hear?",
        options: [option("map", "Map", "🗺️", true), option("mop", "Mop", "🧹"), option("sun", "Sun", "☀️")],
        celebration: "Map! The path across the brook appeared.",
        skill: "Blend map",
        letters: ["m", "a", "p"],
      },
      {
        key: "mat-crossing-sat",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Far Bank",
        prompt: "Sweep s, a, t together. Which word do they make?",
        helper: "Blend smoothly: sssss-aaaaa-t. Sat.",
        spokenPrompt: "Sweep these sounds together: sssss-aaaaa-t. Sat. Which word did you hear?",
        options: [option("sat", "Sat", "🪑", true), option("sit", "Sit", "👇"), option("map", "Map", "🗺️")],
        celebration: "Sat! You reached the far bank.",
        skill: "Blend sat",
        letters: ["s", "a", "t"],
      },
    ],
  ),
  adventure(
    "sun-sail",
    "blend-bridge",
    2,
    "Sail to Sun Island",
    "Blend three sunny words to steer Pip’s leaf boat.",
    "sun-sail",
    "Sun Sail",
    [
      {
        key: "sun-sail-sun",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Raise the Sail",
        prompt: "Sweep s, u, n together. What word?",
        helper: "Keep it smooth: sssss-uh-n. Sun.",
        spokenPrompt: "Sweep these sounds together: sssss-uh-n. Sun. Which word did you hear?",
        options: [option("sun", "Sun", "☀️", true), option("sit", "Sit", "👇"), option("map", "Map", "🗺️")],
        celebration: "Sun! The golden sail popped open.",
        skill: "Blend sun",
        letters: ["s", "u", "n"],
      },
      {
        key: "sun-sail-run",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Catch the Breeze",
        prompt: "Sweep r, u, n together. What word?",
        helper: "Keep it connected: rrrr-uh-n. Run.",
        spokenPrompt: "Sweep these sounds together: rrrr-uh-n. Run. Which word did you hear?",
        options: [option("run", "Run", "🏃", true), option("red", "Red", "🔴"), option("log", "Log", "🪵")],
        celebration: "Run! A playful breeze pushed the boat.",
        skill: "Blend run",
        letters: ["r", "u", "n"],
      },
      {
        key: "sun-sail-fun",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Island Word",
        prompt: "Sweep f, u, n together. What word?",
        helper: "Blend it: fffff-uh-n. Fun.",
        spokenPrompt: "Sweep these sounds together: fffff-uh-n. Fun. Which word did you hear?",
        options: [option("fun", "Fun", "🎉", true), option("fan", "Fan", "🪭"), option("fox", "Fox", "🦊")],
        celebration: "Fun! You sailed all the way to Sun Island.",
        skill: "Blend fun",
        letters: ["f", "u", "n"],
      },
    ],
  ),
  adventure(
    "frog-ferry",
    "blend-bridge",
    3,
    "Frog’s Word Ferry",
    "Blend pond words to help a frog ferry passengers home.",
    "ferry-frog",
    "Ferry Frog",
    [
      {
        key: "frog-ferry-log",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Log Landing",
        prompt: "Sweep l, o, g together. What word?",
        helper: "Blend: lll-ooo-g. Log.",
        spokenPrompt: "Sweep these sounds together: lll-ooo-g. Log. Which word did you hear?",
        options: [option("log", "Log", "🪵", true), option("leg", "Leg", "🦵"), option("sun", "Sun", "☀️")],
        celebration: "Log! The ferry has a landing.",
        skill: "Blend log",
        letters: ["l", "o", "g"],
      },
      {
        key: "frog-ferry-hop",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Hop Aboard",
        prompt: "Sweep h, o, p together. What word?",
        helper: "Blend: hhh-ooo-p. Hop.",
        spokenPrompt: "Sweep these sounds together: hhh-ooo-p. Hop. Which word did you hear?",
        options: [option("hop", "Hop", "🐇", true), option("hat", "Hat", "🎩"), option("map", "Map", "🗺️")],
        celebration: "Hop! The frog jumped aboard.",
        skill: "Blend hop",
        letters: ["h", "o", "p"],
      },
      {
        key: "frog-ferry-fog",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Fog Bell",
        prompt: "Sweep f, o, g together. What word?",
        helper: "Blend: fffff-ooo-g. Fog.",
        spokenPrompt: "Sweep these sounds together: fffff-ooo-g. Fog. Which word did you hear?",
        options: [option("fog", "Fog", "🌫️", true), option("fan", "Fan", "🪭"), option("dog", "Dog", "🐕")],
        celebration: "Fog! The ferry bell guided everyone home.",
        skill: "Blend fog",
        letters: ["f", "o", "g"],
      },
    ],
  ),
  adventure(
    "brook-band",
    "blend-bridge",
    4,
    "The Blend Brook Band",
    "Read the band’s secret word-song without breaking the sounds.",
    "brook-drum",
    "Brook Drum",
    [
      {
        key: "brook-band-red",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Red Drum",
        prompt: "Sweep r, e, d together. What word?",
        helper: "Blend: rrr-eh-d. Red.",
        spokenPrompt: "Sweep these sounds together: rrr-eh-d. Red. Which word did you hear?",
        options: [option("red", "Red", "🔴", true), option("run", "Run", "🏃"), option("bed", "Bed", "🛏️")],
        celebration: "Red! The first drum boomed.",
        skill: "Blend red",
        letters: ["r", "e", "d"],
      },
      {
        key: "brook-band-bed",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Bed Bell",
        prompt: "Sweep b, e, d together. What word?",
        helper: "Blend: bbb-eh-d. Bed.",
        spokenPrompt: "Sweep these sounds together: bbb-eh-d. Bed. Which word did you hear?",
        options: [option("bed", "Bed", "🛏️", true), option("bad", "Bad", "🌧️"), option("red", "Red", "🔴")],
        celebration: "Bed! The silver bell rang.",
        skill: "Blend bed",
        letters: ["b", "e", "d"],
      },
      {
        key: "brook-band-dog",
        regionId: "blend-bridge",
        kind: "blend",
        title: "Dog Dance",
        prompt: "Sweep d, o, g together. What word?",
        helper: "Blend: ddd-ooo-g. Dog.",
        spokenPrompt: "Sweep these sounds together: ddd-ooo-g. Dog. Which word did you hear?",
        options: [option("dog", "Dog", "🐕", true), option("dig", "Dig", "⛏️"), option("log", "Log", "🪵")],
        celebration: "Dog! The whole brook band is playing.",
        skill: "Independent CVC blending",
        letters: ["d", "o", "g"],
      },
    ],
  ),
  adventure(
    "word-sprouts",
    "word-garden",
    1,
    "The First Word Sprouts",
    "Change one middle sound and watch new words grow.",
    "moonflower",
    "Moonflower",
    [
      {
        key: "word-sprouts-sit",
        regionId: "word-garden",
        kind: "word",
        title: "Sat to Sit",
        prompt: "Change sat into sit. Which vowel belongs in the middle?",
        helper: "Stretch sit: sssss-ih-t. Listen to the middle.",
        spokenPrompt: "Change sat into sit. Stretch it: sssss-ih-t. Which vowel belongs in the middle?",
        options: [option("i", "i", undefined, true), option("a", "a", undefined), option("o", "o", undefined)],
        celebration: "Sit! One changed sound grew a new word.",
        skill: "Change middle vowel",
        letters: ["s", "_", "t"],
      },
      {
        key: "word-sprouts-cat",
        regionId: "word-garden",
        kind: "word",
        title: "Mat to Cat",
        prompt: "Change mat into cat. Which letter belongs first?",
        helper: "Cat begins with a sharp kuh sound.",
        spokenPrompt: "Change mat into cat. Cat begins with kuh. Which letter belongs first?",
        options: [option("c", "c", undefined, true), option("m", "m", undefined), option("s", "s", undefined)],
        celebration: "Cat! A whiskery word sprouted.",
        skill: "Change first sound",
        letters: ["_", "a", "t"],
      },
      {
        key: "word-sprouts-map",
        regionId: "word-garden",
        kind: "word",
        title: "Mat to Map",
        prompt: "Change mat into map. Which letter belongs last?",
        helper: "Map ends with a popping p sound.",
        spokenPrompt: "Change mat into map. Map ends with p, a popping sound. Which letter belongs last?",
        options: [option("p", "p", undefined, true), option("t", "t", undefined), option("m", "m", undefined)],
        celebration: "Map! Three word sprouts are blooming.",
        skill: "Change final sound",
        letters: ["m", "a", "_"],
      },
    ],
  ),
  adventure(
    "rhyming-beds",
    "word-garden",
    2,
    "The Rhyming Flowerbeds",
    "Grow word-family flowers by changing their first sound.",
    "sunbell",
    "Sunbell",
    [
      {
        key: "rhyming-beds-cat",
        regionId: "word-garden",
        kind: "word",
        title: "The At Bed",
        prompt: "Add c to at. What word grows?",
        helper: "Blend c with at: c-at.",
        spokenPrompt: "Add the kuh sound to at. Blend them: c-at. What word grows?",
        options: [option("cat", "Cat", "🐈", true), option("sun", "Sun", "☀️"), option("log", "Log", "🪵")],
        celebration: "Cat grew in the at flowerbed.",
        skill: "Word family at",
        letters: ["c", "a", "t"],
      },
      {
        key: "rhyming-beds-run",
        regionId: "word-garden",
        kind: "word",
        title: "The Un Bed",
        prompt: "Add r to un. What word grows?",
        helper: "Blend r with un: r-un.",
        spokenPrompt: "Add rrr to un. Blend them: r-un. What word grows?",
        options: [option("run", "Run", "🏃", true), option("red", "Red", "🔴"), option("rat", "Rat", "🐀")],
        celebration: "Run grew in the un flowerbed.",
        skill: "Word family un",
        letters: ["r", "u", "n"],
      },
      {
        key: "rhyming-beds-dog",
        regionId: "word-garden",
        kind: "word",
        title: "The Og Bed",
        prompt: "Add d to og. What word grows?",
        helper: "Blend d with og: d-og.",
        spokenPrompt: "Add d to og. Blend them: d-og. What word grows?",
        options: [option("dog", "Dog", "🐕", true), option("dig", "Dig", "⛏️"), option("dot", "Dot", "⚫")],
        celebration: "Dog grew in the og flowerbed.",
        skill: "Word family og",
        letters: ["d", "o", "g"],
      },
    ],
  ),
  adventure(
    "vowel-vines",
    "word-garden",
    3,
    "The Tangled Vowel Vines",
    "Choose the middle vowels that untangle Pip’s path.",
    "vowel-vine",
    "Vowel Vine",
    [
      {
        key: "vowel-vines-map",
        regionId: "word-garden",
        kind: "word",
        title: "Map Vine",
        prompt: "Complete m_p to make map.",
        helper: "Map has the open a sound in the middle.",
        spokenPrompt: "Complete the word map. Mmmmm-aaaaa-p. Which vowel belongs in the middle?",
        options: [option("a", "a", undefined, true), option("i", "i", undefined), option("o", "o", undefined)],
        celebration: "Map! The first vine curled away.",
        skill: "Short vowel a",
        letters: ["m", "_", "p"],
      },
      {
        key: "vowel-vines-red",
        regionId: "word-garden",
        kind: "word",
        title: "Red Vine",
        prompt: "Complete r_d to make red.",
        helper: "Red has the quick eh sound in the middle.",
        spokenPrompt: "Complete the word red. Rrr-eh-d. Which vowel belongs in the middle?",
        options: [option("e", "e", undefined, true), option("a", "a", undefined), option("o", "o", undefined)],
        celebration: "Red! Another vine untangled.",
        skill: "Short vowel e",
        letters: ["r", "_", "d"],
      },
      {
        key: "vowel-vines-hop",
        regionId: "word-garden",
        kind: "word",
        title: "Hop Vine",
        prompt: "Complete h_p to make hop.",
        helper: "Hop has the round o sound in the middle.",
        spokenPrompt: "Complete the word hop. Hhh-ooo-p. Which vowel belongs in the middle?",
        options: [option("o", "o", undefined, true), option("a", "a", undefined), option("i", "i", undefined)],
        celebration: "Hop! The path is clear again.",
        skill: "Short vowel o",
        letters: ["h", "_", "p"],
      },
    ],
  ),
  adventure(
    "silly-harvest",
    "word-garden",
    4,
    "The Silly Word Harvest",
    "Read carefully and harvest only the real words.",
    "golden-watering-can",
    "Golden Watering Can",
    [
      {
        key: "silly-harvest-mat",
        regionId: "word-garden",
        kind: "word",
        title: "Mat or Mip",
        prompt: "Which is a real word you can sit on?",
        helper: "Blend both choices. A mat is something you can sit on.",
        options: [option("mat", "mat", "▦", true), option("mip", "mip", "✨"), option("mot", "mot", "✨")],
        celebration: "Mat is a real word. Into the harvest basket!",
        skill: "Read for meaning",
        letters: ["m", "a", "t"],
      },
      {
        key: "silly-harvest-dog",
        regionId: "word-garden",
        kind: "word",
        title: "Dog or Dap",
        prompt: "Which is a real animal word?",
        helper: "Blend each word and think about its meaning.",
        options: [option("dog", "dog", "🐕", true), option("dap", "dap", "✨"), option("dig", "dig", "⛏️")],
        celebration: "Dog is the animal word. Great harvesting!",
        skill: "Read for meaning",
        letters: ["d", "o", "g"],
      },
      {
        key: "silly-harvest-sun",
        regionId: "word-garden",
        kind: "word",
        title: "Sun or Sog",
        prompt: "Which real word shines in the sky?",
        helper: "Blend the choices. Sun shines in the sky.",
        options: [option("sun", "sun", "☀️", true), option("sog", "sog", "✨"), option("sin", "sin", "✨")],
        celebration: "Sun! You harvested a whole basket of real words.",
        skill: "Read for meaning",
        letters: ["s", "u", "n"],
      },
    ],
  ),
  adventure(
    "sam-and-cat",
    "story-stage",
    1,
    "Sam and the Cat",
    "Read a two-line play and remember who joined Sam.",
    "curtain-cat",
    "Curtain Cat",
    [
      {
        key: "sam-cat-read",
        regionId: "story-stage",
        kind: "story",
        title: "Curtain One",
        prompt: "Sam sat. A cat sat with Sam. Who sat with Sam?",
        helper: "The second sentence names the animal.",
        spokenPrompt: "Curtain up! Sam sat. A cat sat with Sam. Who sat with Sam?",
        options: [option("cat", "The cat", "🐈", true), option("dog", "The dog", "🐕"), option("fox", "Pip", "🦊")],
        celebration: "The cat sat with Sam. You read for meaning.",
        skill: "Recall a story detail",
        storyWords: ["Sam", "sat.", "A", "cat", "sat", "with", "Sam."],
      },
      {
        key: "sam-cat-action",
        regionId: "story-stage",
        kind: "story",
        title: "Actor’s Action",
        prompt: "What did Sam and the cat do?",
        helper: "The action word appears twice: sat.",
        spokenPrompt: "Sam sat. A cat sat with Sam. What did they do?",
        options: [option("sat", "They sat", "🪑", true), option("ran", "They ran", "🏃"), option("ate", "They ate", "🍎")],
        celebration: "They sat. You found the action word.",
        skill: "Understand an action",
        storyWords: ["Sam", "sat.", "A", "cat", "sat", "with", "Sam."],
      },
      {
        key: "sam-cat-count",
        regionId: "story-stage",
        kind: "story",
        title: "Final Bow",
        prompt: "How many characters sat together?",
        helper: "Count Sam and the cat.",
        options: [option("two", "Two", "2️⃣", true), option("one", "One", "1️⃣"), option("three", "Three", "3️⃣")],
        celebration: "Two characters! Sam and the cat take a bow.",
        skill: "Combine story details",
        storyWords: ["Sam", "sat.", "A", "cat", "sat", "with", "Sam."],
      },
    ],
    "sam-cat-story",
  ),
  adventure(
    "fox-in-box",
    "story-stage",
    2,
    "Fox in a Box",
    "Discover why a little box keeps giggling.",
    "box-fox",
    "Box Fox",
    [
      {
        key: "fox-box-who",
        regionId: "story-stage",
        kind: "story",
        title: "The Giggling Box",
        prompt: "A box sat on a log. A fox hid in the box. Who hid inside?",
        helper: "The second sentence tells who hid.",
        spokenPrompt: "A box sat on a log. A fox hid in the box. Who hid inside the box?",
        options: [option("fox", "A fox", "🦊", true), option("cat", "A cat", "🐈"), option("frog", "A frog", "🐸")],
        celebration: "A fox hid in the box. Surprise!",
        skill: "Recall who",
        storyWords: ["A", "box", "sat", "on", "a", "log.", "A", "fox", "hid", "in", "the", "box."],
      },
      {
        key: "fox-box-where",
        regionId: "story-stage",
        kind: "story",
        title: "Where Was It?",
        prompt: "Where did the box sit?",
        helper: "Listen to the first sentence: on a log.",
        options: [option("log", "On a log", "🪵", true), option("bed", "On a bed", "🛏️"), option("boat", "On a boat", "⛵")],
        celebration: "The box sat on a log. You remembered where.",
        skill: "Recall where",
        storyWords: ["A", "box", "sat", "on", "a", "log."],
      },
      {
        key: "fox-box-rhyme",
        regionId: "story-stage",
        kind: "rhyme",
        title: "Encore Rhyme",
        prompt: "Which two story words rhyme?",
        helper: "Fox and box share the ending ox.",
        options: [option("fox-box", "Fox and box", "🦊📦", true), option("log-box", "Log and box", "🪵📦"), option("fox-log", "Fox and log", "🦊🪵")],
        celebration: "Fox and box rhyme. The audience giggled.",
        skill: "Notice rhyme in text",
      },
    ],
    "fox-box-story",
  ),
  adventure(
    "red-hat",
    "story-stage",
    3,
    "The Red Hat",
    "Follow a runaway hat through a windy little play.",
    "red-hat",
    "Runaway Red Hat",
    [
      {
        key: "red-hat-owner",
        regionId: "story-stage",
        kind: "story",
        title: "Windy Opening",
        prompt: "Meg had a red hat. The hat fell in the mud. Who owned the hat?",
        helper: "The first sentence tells us who had it.",
        spokenPrompt: "Meg had a red hat. The hat fell in the mud. Who owned the hat?",
        options: [option("meg", "Meg", "🧒", true), option("sam", "Sam", "🧒🏽"), option("pip", "Pip", "🦊")],
        celebration: "Meg owned the red hat.",
        skill: "Identify a character",
        storyWords: ["Meg", "had", "a", "red", "hat.", "The", "hat", "fell", "in", "the", "mud."],
      },
      {
        key: "red-hat-color",
        regionId: "story-stage",
        kind: "story",
        title: "Costume Clue",
        prompt: "What color was Meg’s hat?",
        helper: "The color word comes just before hat.",
        options: [option("red", "Red", "🔴", true), option("blue", "Blue", "🔵"), option("green", "Green", "🟢")],
        celebration: "The hat was red. You spotted the describing word.",
        skill: "Find a describing detail",
        storyWords: ["Meg", "had", "a", "red", "hat."],
      },
      {
        key: "red-hat-where",
        regionId: "story-stage",
        kind: "story",
        title: "Muddy Finale",
        prompt: "Where did the hat fall?",
        helper: "The second sentence ends with the place.",
        options: [option("mud", "In the mud", "🟫", true), option("pond", "In the pond", "💧"), option("box", "In a box", "📦")],
        celebration: "In the mud! You followed the whole little plot.",
        skill: "Recall an event",
        storyWords: ["The", "hat", "fell", "in", "the", "mud."],
      },
    ],
    "red-hat-story",
  ),
  adventure(
    "moon-picnic",
    "story-stage",
    4,
    "Picnic by the Moon",
    "Read the grand finale and solve three clues from one story.",
    "moon-picnic",
    "Moon Picnic",
    [
      {
        key: "moon-picnic-pack",
        regionId: "story-stage",
        kind: "story",
        title: "Pack the Picnic",
        prompt: "Pip had a map and a red cup. He sat by the moonlit pond. What did Pip have?",
        helper: "The first sentence names two things.",
        spokenPrompt: "Pip had a map and a red cup. He sat by the moonlit pond. What did Pip have?",
        options: [option("map-cup", "A map and cup", "🗺️🥤", true), option("hat-log", "A hat and log", "🎩🪵"), option("box-cat", "A box and cat", "📦🐈")],
        celebration: "A map and a red cup. You packed the right things.",
        skill: "Recall two details",
        storyWords: ["Pip", "had", "a", "map", "and", "a", "red", "cup.", "He", "sat", "by", "the", "moonlit", "pond."],
      },
      {
        key: "moon-picnic-place",
        regionId: "story-stage",
        kind: "story",
        title: "Moonlit Place",
        prompt: "Where did Pip sit?",
        helper: "The second sentence names the place.",
        options: [option("pond", "By the pond", "💧", true), option("stage", "On the stage", "🎭"), option("tree", "In a tree", "🌳")],
        celebration: "By the moonlit pond. You found the setting.",
        skill: "Identify setting",
        storyWords: ["He", "sat", "by", "the", "moonlit", "pond."],
      },
      {
        key: "moon-picnic-color",
        regionId: "story-stage",
        kind: "story",
        title: "Final Detail",
        prompt: "What was red?",
        helper: "Look at the words just before cup.",
        options: [option("cup", "The cup", "🥤", true), option("map", "The map", "🗺️"), option("moon", "The moon", "🌙")],
        celebration: "The cup was red. You read a whole story for meaning!",
        skill: "Integrate story details",
        storyWords: ["Pip", "had", "a", "map", "and", "a", "red", "cup."],
      },
    ],
    "moon-picnic-story",
  ),
];

export const STICKERS: Sticker[] = [
  ["echo-shell", "Echo Shell", "🐚", "sound-safari", "It hums back every rhyme."],
  ["rhyme-frog", "Rhyme Frog", "🐸", "sound-safari", "Hops whenever two endings match."],
  ["detective-badge", "Sound Detective", "🔎", "sound-safari", "For finding sounds at the start of words."],
  ["golden-harp", "Golden Echo Harp", "🎵", "sound-safari", "Conducts the meadow’s rhyme festival."],
  ["moon-mouse", "Moon Mouse", "🐭", "letter-lanterns", "Keeper of the humming m lantern."],
  ["silver-snake", "Silver Snake", "🐍", "letter-lanterns", "Whispers the quiet s sound."],
  ["tapping-turtle", "Tapping Turtle", "🐢", "letter-lanterns", "Taps a quick t tune."],
  ["vowel-firefly", "Vowel Firefly", "✨", "letter-lanterns", "Glows inside the middle of words."],
  ["brook-boat", "Leaf Boat", "⛵", "blend-bridge", "Sails only when sounds stay connected."],
  ["sun-sail", "Sun Sail", "☀️", "blend-bridge", "Catches a breeze from a blended word."],
  ["ferry-frog", "Ferry Frog", "🐸", "blend-bridge", "Carries brave readers across the brook."],
  ["brook-drum", "Brook Drum", "🥁", "blend-bridge", "Booms for smooth blends."],
  ["moonflower", "Moonflower", "🌙", "word-garden", "Blooms when one sound changes."],
  ["sunbell", "Sunbell", "🌻", "word-garden", "Rings for every word-family match."],
  ["vowel-vine", "Vowel Vine", "🌿", "word-garden", "Twines around quick middle sounds."],
  ["golden-watering-can", "Golden Watering Can", "🪴", "word-garden", "Waters only real words."],
  ["curtain-cat", "Curtain Cat", "🐈", "story-stage", "Never misses a story cue."],
  ["box-fox", "Box Fox", "🦊", "story-stage", "The theater’s surprise expert."],
  ["red-hat", "Runaway Red Hat", "🎩", "story-stage", "A very dramatic costume."],
  ["moon-picnic", "Moon Picnic", "🧺", "story-stage", "The grand-finale treasure."],
].map(([id, name, icon, regionId, description]) => ({
  id,
  name,
  icon,
  regionId: regionId as ZoneId,
  description,
}));

const STORY_SEEDS: Array<Omit<LibraryStory, "narrationId">> = [
  { id: "moon-mouse-story", title: "Moon Mouse", subtitle: "A humming lantern tale", regionId: "letter-lanterns", lines: ["Mia Mouse had a map.", "The moon lit the map.", "Mia found her mossy home."], unlockAdventureId: "moon-mouse" },
  { id: "fox-box-story", title: "Fox in a Box", subtitle: "A giggling surprise", regionId: "sound-safari", lines: ["A box sat on a log.", "A fox hid in the box.", "The box began to giggle."], unlockAdventureId: "rhyme-river" },
  { id: "sam-cat-story", title: "Sam and the Cat", subtitle: "Two friends take a seat", regionId: "story-stage", lines: ["Sam sat.", "A cat sat with Sam.", "Sam and the cat had a nap."], unlockAdventureId: "sam-and-cat" },
  { id: "red-hat-story", title: "The Red Hat", subtitle: "A windy little play", regionId: "story-stage", lines: ["Meg had a red hat.", "The hat fell in the mud.", "Meg scrubbed it in a tub."], unlockAdventureId: "red-hat" },
  { id: "moon-picnic-story", title: "Picnic by the Moon", subtitle: "Pip’s grand finale", regionId: "story-stage", lines: ["Pip had a map and a red cup.", "He sat by the moonlit pond.", "A frog sang while Pip ate."], unlockAdventureId: "moon-picnic" },
  { id: "sun-island-story", title: "Sun Island", subtitle: "A leaf-boat journey", regionId: "blend-bridge", lines: ["Pip had a sun sail.", "The boat ran with the wind.", "Fun waited on the sand."], unlockAdventureId: "sun-sail" },
  { id: "frog-ferry-story", title: "Frog’s Ferry", subtitle: "A foggy crossing", regionId: "blend-bridge", lines: ["A frog sat on a log.", "Fog hid the far bank.", "The frog rang a bell."], unlockAdventureId: "frog-ferry" },
  { id: "word-sprout-story", title: "The Word Sprout", subtitle: "A tiny garden mystery", regionId: "word-garden", lines: ["Pip put a seed by the mat.", "The seed grew into a map.", "The map showed a secret path."], unlockAdventureId: "word-sprouts" },
  { id: "vowel-vine-story", title: "The Vowel Vine", subtitle: "Three tangled words", regionId: "word-garden", lines: ["A vine hid the map.", "A red bug sat on it.", "Pip had to hop to see."], unlockAdventureId: "vowel-vines" },
  { id: "echo-festival-story", title: "The Echo Festival", subtitle: "The meadow sings", regionId: "sound-safari", lines: ["A goat sailed in a boat.", "A kite danced in the light.", "A shell rang like a bell."], unlockAdventureId: "echo-festival" },
];

export const LIBRARY_STORIES: LibraryStory[] = STORY_SEEDS.map((story) => {
  const narrationId = line(
    `library.${story.id}`,
    `${story.title}. ${story.lines.join(" ")}`,
    "story",
  );
  return { ...story, narrationId };
});

export const GARDEN_PLANTS = [
  { id: "moonflower", name: "Moonflower", icon: "🌙", cost: 1 },
  { id: "sunbell", name: "Sunbell", icon: "🌻", cost: 1 },
  { id: "rhyme-rose", name: "Rhyme Rose", icon: "🌹", cost: 1 },
  { id: "letter-lily", name: "Letter Lily", icon: "🪷", cost: 1 },
  { id: "blend-bush", name: "Blend Berry", icon: "🫐", cost: 1 },
  { id: "story-tree", name: "Story Tree", icon: "🌳", cost: 2 },
  { id: "vowel-vine", name: "Vowel Vine", icon: "🌿", cost: 1 },
  { id: "firefly-fern", name: "Firefly Fern", icon: "✨", cost: 1 },
];

export function adventuresForRegion(regionId: ZoneId) {
  return ADVENTURES.filter((adventure) => adventure.regionId === regionId);
}

export function getAdventure(adventureId: string) {
  return ADVENTURES.find((adventure) => adventure.id === adventureId);
}

export function getDailyAdventure(completedAdventureIds: string[]) {
  const available = ADVENTURES.filter((adventure) => {
    const regionAdventures = adventuresForRegion(adventure.regionId);
    const previous = regionAdventures[adventure.chapter - 2];
    return !previous || completedAdventureIds.includes(previous.id);
  });
  const day = Math.floor(Date.now() / 86_400_000);
  return available[day % available.length] ?? ADVENTURES[0];
}
